//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRM_System1Entities : DbContext
    {
        public CRM_System1Entities()
            : base("name=CRM_System1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCours> tblCourses { get; set; }
        public virtual DbSet<tblModule> tblModules { get; set; }
        public virtual DbSet<tblTechnology> tblTechnologies { get; set; }
        public virtual DbSet<tblTopic> tblTopics { get; set; }
        public virtual DbSet<tblTrainingContent> tblTrainingContents { get; set; }
        public virtual DbSet<tblTrainingFee> tblTrainingFees { get; set; }
    }
}
