//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblModule()
        {
            this.tblTopics = new HashSet<tblTopic>();
        }
    
        public int ModuleId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string ModuleName { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTopic> tblTopics { get; set; }
    }
}
