//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingFee
    {
        public int TrainingFeesId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<decimal> Lumsum { get; set; }
        public Nullable<decimal> Installment { get; set; }
        public Nullable<decimal> RegistrationAmt { get; set; }
    
        public virtual tblCours tblCours { get; set; }
    }
}
