//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTopic
    {
        public int TopicId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string TopicName { get; set; }
    
        public virtual tblModule tblModule { get; set; }
    }
}
