//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrainingContent
    {
        public int TrainingContentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string ContentName { get; set; }
        public Nullable<double> Duration { get; set; }
    
        public virtual tblCours tblCours { get; set; }
    }
}
